import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Scale, Info, X, AlertTriangle, ExternalLink } from 'lucide-react';

// Fixed bottom-right floating disclaimer badge
export const DisclaimerBadge = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isPulsing, setIsPulsing] = useState(false);

  // Pulse every 10 seconds
  useEffect(() => {
    const interval = setInterval(() => {
      setIsPulsing(true);
      setTimeout(() => setIsPulsing(false), 1000);
    }, 10000);
    return () => clearInterval(interval);
  }, []);

  return (
    <>
      <motion.button
        onClick={() => setIsModalOpen(true)}
        className="fixed bottom-6 right-6 z-50 flex items-center gap-2 px-4 py-2.5 rounded-2xl glass backdrop-blur-xl"
        style={{ opacity: 0.85 }}
        initial={{ y: 100, opacity: 0 }}
        animate={{ 
          y: 0, 
          opacity: 0.85,
          scale: isPulsing ? [1, 1.05, 1] : 1,
        }}
        whileHover={{ opacity: 1, scale: 1.02 }}
        transition={{ delay: 1, type: 'spring' }}
        aria-label="Legal disclaimer information"
      >
        <motion.div
          animate={{ 
            boxShadow: isPulsing 
              ? ['0 0 0 0 rgba(var(--primary), 0)', '0 0 0 8px rgba(var(--primary), 0.2)', '0 0 0 0 rgba(var(--primary), 0)']
              : '0 0 0 0 rgba(var(--primary), 0)'
          }}
          className="w-6 h-6 rounded-lg bg-primary/20 flex items-center justify-center"
        >
          <Scale className="w-4 h-4 text-primary" />
        </motion.div>
        <span className="text-sm text-muted-foreground">
          Legal Information, Not Legal Advice
        </span>
      </motion.button>

      {/* Full Disclaimer Modal */}
      <AnimatePresence>
        {isModalOpen && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-background/80 backdrop-blur-sm"
            onClick={() => setIsModalOpen(false)}
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              className="relative max-w-xl w-full p-6 rounded-2xl glass-strong"
              onClick={(e) => e.stopPropagation()}
            >
              <button
                onClick={() => setIsModalOpen(false)}
                className="absolute top-4 right-4 p-2 rounded-lg hover:bg-white/10 transition-colors"
                aria-label="Close disclaimer"
              >
                <X className="w-5 h-5 text-muted-foreground" />
              </button>

              <div className="flex items-center gap-3 mb-4">
                <div className="w-12 h-12 rounded-xl bg-primary/20 flex items-center justify-center">
                  <Scale className="w-6 h-6 text-primary" />
                </div>
                <div>
                  <h2 className="text-xl font-bold">Legal Disclaimer</h2>
                  <p className="text-sm text-muted-foreground">Please read carefully</p>
                </div>
              </div>

              <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
                <p>
                  <strong className="text-foreground">LegalAI provides legal information, not legal advice.</strong> The analysis 
                  generated by our AI is based on general legal principles and the information you provide.
                </p>
                <p>
                  This tool is designed to help you understand potential legal frameworks that may apply 
                  to your situation. It should not be considered as a substitute for professional legal counsel.
                </p>
                <p>
                  <strong className="text-foreground">Actual legal outcomes depend on:</strong>
                </p>
                <ul className="list-disc list-inside space-y-1 ml-2">
                  <li>Specific facts and circumstances of your case</li>
                  <li>Available evidence and documentation</li>
                  <li>Jurisdiction and applicable state laws</li>
                  <li>Court discretion and interpretation</li>
                  <li>Legal representation quality</li>
                </ul>
                <p className="text-primary font-medium">
                  Always consult a qualified legal professional before making any legal decisions.
                </p>
              </div>

              <motion.button
                onClick={() => setIsModalOpen(false)}
                className="w-full mt-6 py-3 rounded-xl bg-primary text-primary-foreground font-medium"
                whileHover={{ scale: 1.02 }}
                whileTap={{ scale: 0.98 }}
              >
                I Understand
              </motion.button>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
};

// Prominent warning card for results section
export const ImportantDisclaimerCard = () => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="p-4 rounded-xl border-l-4 border-yellow-500"
      style={{
        background: 'linear-gradient(135deg, rgba(234, 179, 8, 0.1) 0%, rgba(251, 146, 60, 0.05) 100%)',
        border: '1px solid rgba(234, 179, 8, 0.2)',
        borderLeft: '4px solid rgb(234 179 8)',
      }}
    >
      <div className="flex gap-3">
        <div className="flex-shrink-0">
          <AlertTriangle className="w-5 h-5 text-yellow-500" />
        </div>
        <div>
          <h4 className="font-semibold text-yellow-500 mb-1">Important Notice</h4>
          <p className="text-sm text-muted-foreground leading-relaxed">
            This analysis is based on information provided and general legal principles. 
            Actual outcomes depend on specific facts, evidence, jurisdiction, and court discretion. 
            <strong className="text-foreground"> Consult a qualified lawyer for your situation.</strong>
          </p>
        </div>
      </div>
    </motion.div>
  );
};

// Small probabilistic estimate text
export const ProbabilisticEstimateNote = () => {
  return (
    <motion.p
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="flex items-center gap-2 text-xs text-muted-foreground"
    >
      <Info className="w-3 h-3" />
      Results are probabilistic estimates based on available data
    </motion.p>
  );
};

// Uncertainty messaging component
export const UncertaintyBadges = ({ type }: { type: 'bail' | 'punishment' | 'general' }) => {
  const badges = {
    bail: [
      { label: 'State', icon: '📍' },
      { label: 'Evidence Quality', icon: '📋' },
      { label: 'Judge Discretion', icon: '⚖️' },
    ],
    punishment: [
      { label: 'Prior Record', icon: '📁' },
      { label: 'Circumstances', icon: '🔍' },
      { label: 'Plea Bargain', icon: '🤝' },
    ],
    general: [
      { label: 'State', icon: '📍' },
      { label: 'Evidence Quality', icon: '📋' },
      { label: 'Judge Discretion', icon: '⚖️' },
    ],
  };

  return (
    <div className="flex flex-wrap gap-2 mt-2">
      <span className="text-xs text-muted-foreground">May vary by:</span>
      {badges[type].map((badge) => (
        <span
          key={badge.label}
          className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-white/5 border border-white/10 text-xs text-muted-foreground"
        >
          <span>{badge.icon}</span>
          {badge.label}
        </span>
      ))}
    </div>
  );
};

// Confidence badge for quick stats
export const ConfidenceBadge = ({ 
  value, 
  label = 'Probability' 
}: { 
  value: number; 
  label?: string;
}) => {
  const getConfidenceLevel = (v: number) => {
    if (v >= 70) return { text: 'High', color: 'text-green-400 bg-green-400/10' };
    if (v >= 40) return { text: 'Medium', color: 'text-yellow-400 bg-yellow-400/10' };
    return { text: 'Low', color: 'text-orange-400 bg-orange-400/10' };
  };

  const level = getConfidenceLevel(value);

  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs ${level.color}`}>
      {label}: {value}% ({level.text} confidence)
    </span>
  );
};
